// Last Generated: 2011-08-25T23:29:48-04:00
package com.shopify.api.resources;

import java.io.File;
import java.util.List;

import org.codehaus.jackson.annotate.JsonIgnore;
import org.codehaus.jackson.annotate.JsonProperty;

/**
* This code has been machine generated by processing the single entry
* fixtures found from the Shopify API Documentation
*/
  
public class Image extends MGImage {
	private static final String FILENAME = "filename";
	private static final String ATTACHMENT = "attachment";
	private static final String POSITION = "position";
	
	private File image;
	
	@JsonIgnore
	public void setImage(File image) {
		this.image = image;
	}
	
	@JsonIgnore
	public File getImage() {
		return image;
	}
	
	public void setFilename(String filename) {
		setAttribute(FILENAME, filename);
	}
	
	public String getFilename() { return (String) getAttribute(FILENAME); }
	
	public void setPosition(int position) {
		setAttribute(POSITION, new Integer(position));
	}
	
	public int getPosition() {
		return ((Integer) getAttribute(POSITION)).intValue();
	}
	
	@JsonProperty("variant_ids")
	public List<Integer> getVariantIds() {
		return (List<Integer>)getAttribute("variant_ids");
	}
	@JsonProperty("variant_ids")
	public void setVariantIds(List<Integer> _variant_ids) {
		setAttribute("variant_ids", _variant_ids);
	}
}