// Last Generated: 2011-08-25T23:29:48-04:00
/**
 * Modified by Jay on Oct. 30, 2012.
 * Shopify API may changed the returned data. Previously, there was no product_id and position property in Option class. Then, the properties were added, resulting
 * in a mapping exception for the Option class. By adding get and set methods for productId and position, this change was adopted. 
 * 
 */
package com.shopify.api.resources;

import java.util.List;

import org.codehaus.jackson.annotate.JsonProperty;

/**
* This code has been machine generated by processing the single entry
* fixtures found from the Shopify API Documentation
* 
* Modified by Jay on July 6, 2015
* Shopify API added weight and values for Option
* 
*/
  
public class Option extends MGOption {

	@JsonProperty("product_id")
	public String getProductId() {
		return (String)getAttribute("product_id");
	}
	@JsonProperty("product_id")
	public void setProductId(String _product_id) {
		setAttribute("product_id", _product_id);
	}
	
	@JsonProperty("position")
	public int getPosition() {
		return (Integer) getAttribute("position");
	}
	@JsonProperty("position")
	public void setPosition(int _position) {
		setAttribute("position", _position);
	}

	@JsonProperty("values")
	public List<String> getValues() {
		return (List<String>)getAttribute("values");
	}
	@JsonProperty("values")
	public void setValues(List<String> _values) {
		setAttribute("values", _values);
	}

}