// Last Generated: 2011-08-25T23:29:48-04:00
/**
 * Modified by Jay on May 29, 2012.
 * Shopify API may changed the returned data. Previously, there was no product_id property in Variant class. Then, the product_id property was added, resulting
 * in a mapping exception for the Variant class. By adding get and set methods for productId, this change was adopted. 
 * 
 * Modified by Jay on Nov. 11, 2014
 * Shopify API added image_id for Variant
 * 
 * Modified by Jay on July 6, 2015
 * Shopify API added weight and weight unit for Variant
 * 
 * Position
 */
package com.shopify.api.resources;

import org.codehaus.jackson.annotate.JsonProperty;

/**
* This code has been machine generated by processing the single entry
* fixtures found from the Shopify API Documentation
*/
  
public class Variant extends MGVariant {

	@JsonProperty("product_id")
	public String getProductId() {
		return (String)getAttribute("product_id");
	}
	@JsonProperty("product_id")
	public void setProductId(String _product_id) {
		setAttribute("product_id", _product_id);
	}
	
	@JsonProperty("position")
	public int getPosition() {
		return (Integer) getAttribute("position");
	}
	@JsonProperty("position")
	public void setPosition(int _position) {
		setAttribute("position", _position);
	}
	
	@JsonProperty("barcode")
	public String getBarcode() {
		return (String)getAttribute("barcode");
	}
	@JsonProperty("barcode")
	public void setBarcode(String _barcode) {
		setAttribute("barcode", _barcode);
	}
	
	@JsonProperty("image_id")
	public String getImageId() {
		return (String)getAttribute("image_id");
	}
	@JsonProperty("image_id")
	public void setImageId(String _image_id) {
		setAttribute("image_id", _image_id);
	}

	@JsonProperty("weight")
	public float getWeight() {
		return (Float)getAttribute("weight");
	}
	@JsonProperty("weight")
	public void setWeight(float _weight) {
		setAttribute("weight", _weight);
	}

	@JsonProperty("weight_unit")
	public String getWeightUnit() {
		return (String)getAttribute("weight_unit");
	}
	@JsonProperty("weight_unit")
	public void setWeightUnit(String _weight_unit) {
		setAttribute("weight_unit", _weight_unit);
	}

}